JuliaAI/DecisionTree.jl

.travis.yml, README.md
Hi @bensadeghi 
I really like this package, and I thought it might be nice to add these "badges", and enable TravisCI and Coveralls (for code coverage reporting). Apart from the utility of these services themselves, there is also the "signal" they send that this package is in excellent condition.
I can't enable these services myself, but with this PR all you should have to do is turn them on and it should all "just work"
=> Add badges, continuous integeration

src/regression.jl
I replaced the O(N^2) threshold selection algorithm with an O(N) version. On my benchmark,
```julia
using Benchmarks
Profile.clear()
srand(2)
N = 3000
X = randn(N, 10)
y = randn(N)
model = fit!(DecisionTree.RandomForestRegressor(), X, y)
@benchmark fit!(DecisionTree.RandomForestRegressor(), X, y)
```
it is twice as fast as `master`. It should be mathematically exactly the same as before, but there's a handful of branches that are different. I blame floating point inaccuracy... but I'm not so sure.... the computation for `s_r` and `s2_r` is not floating-point-equivalent, so presumably over all the comparisons that DecisionTree makes in fitting a tree, it can make a difference at some point? All tests pass, but please review carefully.
I took `for thresh in domain[2:end]` from your code and …
=> Improved learning speed

README.md, src/classification.jl, src/regression.jl, src/scikitlearnAPI.jl, test/classification_scikitlearn.jl, test/regression_scikitlearn.jl
I started off from @trouve-antoine's PR and went from there.
One minor note: `maxdepth=8` yields `depth(::Tree)=7`. Wikipedia agrees with you that leaves have depth=0:
> The depth of a node is the length of the path to its root (i.e., its root path)
so I should probably correct the `maxdepth` arguments to reflect that.
=> Added the maxdepth parameter

src/DecisionTree.jl, src/classification.jl
With this change, I can see an upto 30% reduction in the execution time for the `apply_forest` method for large models. 
This still is not perfect, since `Node` contains an `Union`. However, there is hope that some of the upcoming improvements in Base will cover this. 
cc: @bensadeghi
=> Improve performance by improving type stability

src/DecisionTree.jl, src/classification.jl
There are ~~two~~ one major change~~s~~. First thing is to wrap most of the body in a function to avoid type instability in a relatively hot loop caused by `inds`. ~~The other improvement is to use merge sort in `sortperm` which happens to be much faster for feature vectors.~~
=> Speed up _split_info_gain

src/DecisionTree.jl, src/classification.jl
Reverting commit [1c8c3f7c08bbb5ed1cdd9ce9ea1c1fe9bb7b1fb6](https://github.com/bensadeghi/DecisionTree.jl/commit/1c8c3f7c08bbb5ed1cdd9ce9ea1c1fe9bb7b1fb6)
"make apply-* methods faster, by making summarize_votes type stable " 
The new ```Node``` definition was breaking training with heterogeneously typed features, and also certain ```build_forest``` runs where Leafs need to be promoted to Nodes.
=> reverting to old Node

src/DecisionTree.jl, src/classification/main.jl, src/classification/tree.jl, src/measures.jl, src/regression/main.jl, src/regression/tree.jl, src/scikitlearnAPI.jl, src/util.jl, test/bench/trees.jl, test/classification/digits.jl, test/classification/scikitlearn.jl, test/regression/digits.jl, test/runtests.jl
- minor style fixes
- now internally support weights! (though API is not yet exposed)
- now internally support passing purity criteria! (though API is not yet exposed)
- add `treeclassifier.fit_zero_one` for fitting with zero one loss
- classification's `build_stump` now calls `treeclassifier.fit_zero_one` internally.
- small (~2-3%) performance increase for classification's `build_tree`, despite new internal support for weights due to type optimisations.
- moderate (~9%) performance degradation for regression's `build_tree` due to internal support for weights. We do not expect this much degradation for adding a feature ever again.
- added type parameters to `NodeMeta` to help optimise memory usage.
Memory optimisations for writing to disk will follow soon.
=> minor fixes and changes

src/classification/tree.jl, src/regression/tree.jl
In `src/regression/tree.jl`:
- Removed unused variable
- Fixed typo, changing `Y` to `W`
In both `src/classification/tree.jl` and `src/regression/tree.jl`:
- Removed a few `Int()`s. Based on what they were used on (and the fact that the unused variable above wasn't causing issues), it seemed like these were unnecessary.
=> Misc small fixes in tree.jl files

src/classification/main.jl, src/classification/tree.jl
`treeclassifier.fit_zero_one` seems to only differ from `treeclassifier.fit` by having a fixed loss function, and seems to only be used once, in `build_stump`. Can it be removed and have `build_stump` call `fit`, as done here, or is `fit_zero_one` being kept for other purposes?
=> Remove fit_zero_one?

.github/workflows/CompatHelper.yml, Manifest.toml, Project.toml, REQUIRE
This PR contains compat fixes so that https://github.com/JuliaRegistries/General/pull/6166 (and future releases) can be automerged.
Specifically, this PR makes the following changes:
1. Adds upper-bounded `[compat]` entry for `julia`
2. Adds upper-bounded `[compat]` entry for `ScikitLearnBase`
3. Drops support for Julia 0.7.
4. Bumps version to `0.10.0` - this is necessary because we are dropping support for Julia 0.7, and you cannot drop support for a Julia version in a patch release.
5. Delete the `REQUIRE` file, which is no longer necessary.
6. Set up CompatHelper, which will make automated PRs to your repo to keep your compat entries up to date. CompatHelper will update both your Project.toml and Manifest.toml files.
=> Compat fixes

src/classification/tree.jl, test/classification/digits.jl
It looks like the classification code was generalized to allow a passed-in <s>loss</s> purity function in [this commit](https://github.com/bensadeghi/DecisionTree.jl/commit/7c40a297829c055e57c6f76d4215227f4fcba66b). However, one `util.entropy` was left in the code. It looks like that should have also been replaced. This PR replaces it, and adds a test. The test gives depth = 1 (i.e., fails) before replacing the `util.entropy`.
=> Replace leftover util.entropy

src/classification/tree.jl, src/regression/tree.jl
I found that I was getting different results for the same problem with the same RNG across different Julia versions (even after accounting for the RNG changes in Julia 1.5). 
The differences seem to show up when there are multiple features with the same best split position, but because of differences between the Julia versions, the actual purity values are slightly different in the last digits, e.g. `9.893954468378139` vs `9.893954468378137`, and this causes different features to be chosen on each version.
This change simply adds a small tolerance to the purity check, which ensures that changes in the last digits won't affect which feature is selected as best.
=> Add tolerance for best_purity checks

src/classification/tree.jl, src/regression/tree.jl
Thanks so much for the fast merge on #119  
I missed that the added check is not robust to the scaling of the data. This fixes that by using `isapprox` rather than an absolute tolerance, so it should work consistently across inputs.
Sorry for the noise and missing this, and thanks again!
=> Fix #119 to work regardless of data scaling

src/classification/tree.jl, src/regression/tree.jl
This PR follows #128 and changes `Matrix` to `AbstractMatrix` in other places that were missed in the original PR.
=> Allow fitting using AbstractMatrix instead of Matrix

src/measures.jl
I believe there is a bug in the cross validation, where the full data is used instead of the data designated for training.
=> calibrate using training data for cross validation

src/classification/tree.jl, src/regression/tree.jl, src/util.jl
The `check_input` function tests if the given tree hyper-parameters are valid. Before this PR, the function was present in both classification and regression code. This PR removes the duplicate code by moving the function to `utils.jl`.
=> Move `check_input` to utils to avoid duplicate code

README.md
As each MLJ DecisionTree.jl model has a detailed doc-string, a short description suffices.
=> Add MLJ usage instructions

src/DecisionTree.jl
This PR is a suggestion to make the print output of `print_tree` easier to understand without context.
```
Feature 3, Threshold -28.166052806422238
L-> Feature 2, Threshold -161.04351901384842
L-> 5 : 842/3650
R-> 7 : 2493/10555
R-> Feature 7, Threshold 108.1408338577021
L-> 2 : 2434/15287
R-> 8 : 1227/3508
```
```
Feature 3 < -28.156052806422238 ?
├─ Feature 2 < -161.04351901384842 ?
├─ 5 : 842/3650
└─ 7 : 2493/10555
└─ Feature 7 < 108.1408338577021 ?
├─ 2 : 2434/15287
└─ 8 : 1227/3508
```
=> Replace `L` by `<` and `R` by `≥`

src/DecisionTree.jl, src/abstract_trees.jl, src/classification/main.jl, src/classification/tree.jl, src/measures.jl, src/regression/main.jl, src/regression/tree.jl, src/scikitlearnAPI.jl, src/util.jl, test/classification/adult.jl, test/classification/digits.jl, test/classification/iris.jl, test/classification/low_precision.jl, test/classification/scikitlearn.jl, test/miscellaneous/convert.jl, test/miscellaneous/feature_importance_test.jl, test/regression/random.jl, test/runtests.jl
=> Feature importance

src/DecisionTree.jl
This fixes the type piracy on `zero`. In #182, @yufongpeng has correctly changed
```julia
zero(String) = ""
```
to
```julia
zero(::Type{String}) = ""
```
because with the old implementation in DecisionTree 0.10, the following happens
```julia
julia> using Statistics
julia> mean([[1, 2]]; dims=1)
1-element Vector{Vector{Float64}}:
[1.0, 2.0]
julia> using DecisionTree
julia> mean([[1, 2]]; dims=1)
ERROR: MethodError: no method matching +(::String, ::String)
[...]
```
since
```julia
julia> zero(String) = ""
julia> zero(1)
""
```
which used to be a very bad type piracy which was luckily solved already by Yu-Fong, Peng.
However, it's still a type piracy because `String` is not owned by `DecisionTree`.
Let's go for some extra safety by adding an intermediate function.
=> Fix type piracy on `zero`

src/classification/main.jl, test/classification/adult.jl, test/classification/digits.jl, test/classification/heterogeneous.jl, test/classification/iris.jl, test/classification/low_precision.jl, test/classification/random.jl, test/regression/digits.jl, test/regression/low_precision.jl
Replaces #176 after rebasing off dev
=> Multithreading for random forest predictions

.gitignore, src/abstract_trees.jl
As there is now an abstract type `AbstractNode` in `AbstractTrees.jl` the "wrapped" decision tree (or rather its nodes) is now defined as a subtype of this `AbstractNode` so that dispatch on this type is possible when the tree gets plotted via a plot recipe.
=> Adapt to new `AbstractNode` in `AbstractTrees`

src/classification/main.jl, src/regression/main.jl
Fixes #194.
Using `rand(_rng, i)` didn't really put all copies of `rng` into a unique state, the states were still interlocked (all the generators produced same sequence of random numbers with some offset). Calling ` seed!` with a deterministic, pseudo-random seed for each thread produces much better results, which is also visible in the classification and regression accuracies produced by the tests.
Here is the diff output of the unit tests before and after the change:
```diff
89c89
< Mean Accuracy: 0.8748748748748749
---
> Mean Accuracy: 0.8998998998998999
91c91
< Mean Accuracy: 0.8448448448448449
---
> Mean Accuracy: 0.9019019019019018
93c93
< Mean Accuracy: 0.8748748748748749
---
> Mean Accuracy: 0.8998998998998999
95c95
< Mean Accuracy: 0.8748748748748749
---
> Mean Accuracy: …
```
=> Use seed! to put every copy of rng into a unique state

Project.toml, README.md, src/classification/main.jl, src/regression/main.jl
=> For a 0.12.0 release

src/abstract_trees.jl, test/miscellaneous/abstract_trees_test.jl
- `printnode` is now rounding the thresholds to `sigdigits` significant digits (`sigdigits` is a keyword parameter)
- the label "Class: " is only printed/plotted within leaves, if ids are used as 'class names'
- a clarification and a check has been added, that you cannot add class names with `wrap` if there are already class names in use (i.e. existing class names cannot be _overriden_, they can only be _added_ if ids are used within the original decision tree structure).
=> Improved label printing/plotting of nodes/leaves

Project.toml, README.md
=> For a 0.12.1 release

Project.toml
=> Bump AbstractTrees.jl compat for 0.12 series

src/classification/main.jl
The keyword is currently undocumented. Closes #134
=> document use_multithreading keyword

src/classification/main.jl
Here's how it displays:
<details>
build_forest(labels, features, options...; keyword_options...)
Train a random forest model, built on standard CART decision trees, using the specified
`labels` (target) and `features` (patterns). Here:
- `labels` is any `AbstractVector`. If the element type is `Float64`, regression is
applied, and otherwise classification is applied.
- `features` is any `AbstractMatrix{T}` where `T` supports ordering with `<` (unordered
categorical features are not supported). The matrix must have size `(n, p)` where `n =
length(labels)` (observations as rows).
Entropy loss is used for determining node splits, i.e., individual trees are trained by
calling `build_tree` with the `loss=DecisionTree.util.entropy` option.
Use [`apply_forest`](@ref) and …
=> Add docstring for `build_forest`

src/DecisionTree.jl, src/classification/main.jl, test/classification/adding_trees.jl, test/miscellaneous/ensemble_methods.jl, test/runtests.jl
Closes #213.
You can now do this:
```julia
features, labels = load_data("iris")
model1 = build_forest(labels, features, 2, 150) # n_trees = 150
model = build_forest(model1, labels, features, 2, 50) # add 50 trees
```
New docstring below.
<details>
build_forest(model, labels, features, options...; keyword_options...)
Return an updated version of `model` with additional `n_trees=options[2]` added to the
forest. Here `options` and `keyword_options` are as for the regular `build_forest` method,
which excludes the `model` argument.
Even if training data is the same in all `build_forest` calls, it is not practically
possible to guarantee adding trees in steps is identical to adding them all at once,
because of the way random number generators are generated and used. But in all other
respects …
=> Add method `build_forest(model, ...)` to add trees to existing `model`

Project.toml, src/classification/main.jl, src/measures.jl, src/regression/main.jl, src/regression/tree.jl, test/regression/low_precision.jl
Based on #225. 
Occurunces of Float64 related to labels were replaced by AbstractFloat.
Problem noted in https://github.com/JuliaAI/DecisionTree.jl/issues/225#issuecomment-1728241680 still not solved as requare more refactor of parameters. But origin issue solved and now other Float type than Float64 will lead to regression, not calssification. 
Also, I see a little perfomance boost and reducing number of allocations on my data.
=> Float64 replaced by AbstractFloat for regression
