src/classification.jl
src/regression.jl
src/scikitlearnAPI.jl
test/classification_scikitlearn.jl
test/regression_scikitlearn.jl

I added explicit RNG support for Adaboost too, only to realize that it's not using the RNG... Right? If that's the case, then I can remove it before merging.

Explicit RNG support

---

src/classification.jl
src/scikitlearnAPI.jl

See https://github.com/bensadeghi/DecisionTree.jl/pull/45#issuecomment-317187708

Fix handling of depth-0 (only leaf) trees in scikit-learn API

---

README.md

Thank you for a nice package.
I found notation differences of README, so fixed it.

fix notation of README

---

REQUIRE
src/DecisionTree.jl
src/classification.jl
src/measures.jl
src/regression.jl
test/classification_hetero.jl

Remove Compat dependency since it is no longer used
This can be even cleaner if the Julia 0.5 requirement is removed but I don't know if you are ready for that yet.

Update code to Julia 0.6 and remove definitions that are no longer needed

---

README.md
src/classification/main.jl
src/measures.jl
src/regression/main.jl
src/scikitlearnAPI.jl
test/classification/random.jl
test/classification/scikitlearn.jl
test/regression/random.jl
test/regression/scikitlearn.jl

Changed some parameter names:
* niterations -> n_iterations
* partialsampling -> partial_sampling
* maxdepth -> max_depth
* nsubfeatures -> n_subfeatures
* ntrees -> n_trees

Param names

---

test/classification/adult.jl
test/classification/iris.jl
test/classification/random.jl

* added adaboost tests
* fix deprecated readcsv()

Minor update to Julia-0.7 branch

---

README.md
TODO.md
src/measures.jl
src/regression/main.jl
src/scikitlearnAPI.jl
test/regression/digits.jl
test/regression/int32_precision.jl
test/regression/random.jl

* Moved `min_samples_leaf` argument for regression `build_tree`
* Updated SKL API
* Updated tests

Regression Tree - move min_samples_leaf arg 

---

README.md
src/classification/main.jl
src/classification/tree.jl
src/regression/main.jl
src/regression/tree.jl
src/scikitlearnAPI.jl
test/classification/random.jl
test/regression/random.jl

* make default `n_subfeatures = round(sqrt(n_features))`
* use `n_subfeatures = -1` in APIs

Forest default n_subfeatures

---

src/DecisionTree.jl
src/classification/main.jl
src/classification/tree.jl
src/regression/main.jl
src/util.jl

I've been making good use of this library but needed it to be a bit faster so made a few optimizations. Specifically:
* Use Threads instead of Distributed
* Do some precomputation to make entropy computation faster
* Use views when evaluating.
This ended up being quite a lot faster for my use case (~200 samples with ~200000 features), but I haven't done any rigorous benchmarking.

Optimization

---

src/classification/tree.jl
src/regression/tree.jl

(sorry to bother you again)
I sent #131 yesterday, yet it was not enough and I did not think to check it. This PR should finally allow fitting using `AbstractMatrix`.

Fitting using AbstractMatrix instead of Matrix

---

src/DecisionTree.jl

Introduced in #142 (CI wasn't in place)

Fix feature_names kwarg structure for julia 1.0

---

.github/workflows/CI.yml
README.md
src/DecisionTree.jl

@bensadeghi If you are seeing this, perhaps you want to update your fork to redirect here, to save confusion (stop you getting PR's, for example). Or your can make your fork private.

Update readme to reflect new ownership

---

test/classification/iris.jl
test/regression/digits.jl

Some fails in Julia 1.0 tests are failing intermittently for one of the 3 platforms tested. This PR relaxes a few tolerances.

Relax some test tolerances

---

README.md
src/DecisionTree.jl
src/classification/main.jl
test/runtests.jl

Stop exporting measures

---

src/DecisionTree.jl
test/miscellaneous/convert.jl
test/runtests.jl

I was trying to bump [`JuliaAI/MLJDecisionTreeInterface.jl`](https://github.com/JuliaAI/MLJDecisionTreeInterface.jl) but got a test error on of the `print_tree` methods. This PR fixes the error.

Fix `print_tree`

---

Project.toml
src/classification/main.jl
src/measures.jl
src/scikitlearnAPI.jl

For a 0.11.1 release

---

Project.toml

For a 0.12.2 release

---

.github/workflows/CI.yml
Project.toml

Bump AbstractTrees compat for 0.11 series

---

.JuliaFormatter.toml

In response to https://github.com/JuliaAI/DecisionTree.jl/pull/219#issuecomment-1431990296.

Add `.JuliaFormatter.toml`

---

README.md

Fix link to MLJ
